In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

2026-06-16 13:37:19.466067: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1781617039.798663      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781617039.880611      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781617040.650037      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781617040.650122      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781617040.650125      58 computation_placer.cc:177] computation placer alr

In [3]:
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts([faqs])

In [5]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [6]:
for sentence in faqs.split('\n'):
    print(sentence)

About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a sessi

In [7]:
for sentence in faqs.split('\n'):
    print(tokenizer.texts_to_sequences([sentence]))

[[93, 1, 13]]
[[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]]
[[1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70, 45]]
[[11, 7, 1, 71, 72, 6, 1, 12]]
[[1, 71, 72, 6, 1, 12, 7, 54, 73, 32, 1, 71, 12, 42, 149, 70, 54, 31, 55, 150]]
[[11, 7, 1, 96, 6, 1, 68, 13]]
[[27, 9, 19, 151, 1, 152, 153]]
[[97, 154]]
[[97, 155, 15, 43, 53]]
[[43, 156]]
[[157, 15, 43, 53]]
[[158, 15, 159, 74]]
[[98, 160]]
[[161, 98]]
[[162]]
[[75, 99]]
[[2, 10, 163, 1, 164, 96, 76, 77, 100, 33, 14, 165, 33, 43, 53, 68, 13, 166]]
[[9, 101, 74, 20, 102, 19, 5, 78, 6, 21, 13]]
[[103, 102, 20, 101, 74, 167, 56, 46, 5, 78, 6, 21, 168, 169]]
[[11, 22, 3, 104, 5, 105, 34, 9, 3, 47, 5, 106, 6, 1, 34]]
[[48, 16, 35, 17, 56, 170, 32, 107, 22, 2, 104, 5, 34, 2, 10, 171, 172, 20, 57, 1, 106]]
[[30, 10, 3, 173, 1, 108, 174]]
[[175, 21, 58, 176, 4, 79, 45, 59, 45, 109, 177, 6, 1, 12, 77, 178, 58, 60, 179, 180, 181, 182, 183, 184, 185]]
[[11, 7, 1, 109, 72, 6, 16, 1, 105, 17]]
[[186, 16, 1, 17, 187, 110, 188]]
[[11, 

In [8]:
for sentence in faqs.split('\n'):
    print(tokenizer.texts_to_sequences([sentence])[0])

[93, 1, 13]
[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]
[1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70, 45]
[11, 7, 1, 71, 72, 6, 1, 12]
[1, 71, 72, 6, 1, 12, 7, 54, 73, 32, 1, 71, 12, 42, 149, 70, 54, 31, 55, 150]
[11, 7, 1, 96, 6, 1, 68, 13]
[27, 9, 19, 151, 1, 152, 153]
[97, 154]
[97, 155, 15, 43, 53]
[43, 156]
[157, 15, 43, 53]
[158, 15, 159, 74]
[98, 160]
[161, 98]
[162]
[75, 99]
[2, 10, 163, 1, 164, 96, 76, 77, 100, 33, 14, 165, 33, 43, 53, 68, 13, 166]
[9, 101, 74, 20, 102, 19, 5, 78, 6, 21, 13]
[103, 102, 20, 101, 74, 167, 56, 46, 5, 78, 6, 21, 168, 169]
[11, 22, 3, 104, 5, 105, 34, 9, 3, 47, 5, 106, 6, 1, 34]
[48, 16, 35, 17, 56, 170, 32, 107, 22, 2, 104, 5, 34, 2, 10, 171, 172, 20, 57, 1, 106]
[30, 10, 3, 173, 1, 108, 174]
[175, 21, 58, 176, 4, 79, 45, 59, 45, 109, 177, 6, 1, 12, 77, 178, 58, 60, 179, 180, 181, 182, 183, 184, 185]
[11, 7, 1, 109, 72, 6, 16, 1, 105, 17]
[186, 16, 1, 17, 187, 110, 188]
[11, 7, 1, 189, 190, 59, 1, 191, 192, 1, 17]
[193]
[111,

In [9]:
input_sequences = []
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [10]:
input_sequences

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [11]:
[len(x) for x in input_sequences]

[2,
 3,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 2,
 2,
 3,
 4,
 5,
 2,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 2,
 2,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 2,
 3,
 4,
 5,
 6,
 7,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 3,
 4,
 5,
 6,
 7,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11

In [12]:
max([len(x) for x in input_sequences])

57

In [13]:
max_len = max([len(x) for x in input_sequences])

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [15]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]], shape=(863, 57), dtype=int32)

In [16]:
padded_input_sequences[:, :-1]

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], shape=(863, 56), dtype=int32)

In [17]:
X = padded_input_sequences[:, :-1]

In [18]:
padded_input_sequences[:, -1]

array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [19]:
y = padded_input_sequences[:, -1]

In [20]:
X.shape

(863, 56)

In [21]:
y.shape

(863,)

In [22]:
len(tokenizer.word_index)

282

In [23]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = 283)

In [24]:
y.shape

(863, 283)

In [25]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(863, 283))

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [27]:
model = Sequential()

model.add(Embedding(283, 100, input_length = 56))
model.add(LSTM(150))
model.add(Dense(283, activation = 'softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2026-06-16 13:37:38.610299: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [28]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [29]:
model.build(input_shape=(None, 56))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], shape=(863, 56), dtype=int32)

In [31]:
model.fit(X, y, epochs = 100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.0637 - loss: 5.4662
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.0776 - loss: 5.1007
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.0776 - loss: 5.0151
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.0776 - loss: 4.9575
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.0811 - loss: 4.8803
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.0915 - loss: 4.7646
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.1228 - loss: 4.5886
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.1495 - loss: 4.3953
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.1611 - loss: 4.1731
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.1877 - loss: 3.9742
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.2144 - loss: 3.7611
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

In [32]:
text = "mail"

#tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0 61]]


In [33]:
#predict
model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step


array([[3.39833775e-07, 2.63038068e-03, 4.23160754e-03, 2.25318181e-05,
        5.52601414e-04, 8.87208036e-04, 7.10315886e-04, 2.41451780e-03,
        3.21004154e-06, 3.50645860e-04, 2.30492446e-06, 3.48799294e-05,
        2.47766124e-03, 8.54399928e-04, 7.54319553e-05, 2.47406643e-02,
        7.22198114e-02, 2.84338207e-03, 6.82636863e-03, 4.35082211e-06,
        2.29791133e-03, 7.06287334e-04, 1.29823253e-04, 7.37453774e-07,
        2.27082684e-03, 3.61048937e-04, 9.94329184e-06, 1.03963900e-03,
        5.52646707e-05, 1.41343364e-04, 5.95241772e-06, 3.01320339e-04,
        2.07859295e-04, 1.40253454e-03, 5.99950654e-05, 4.94897319e-03,
        4.63123841e-04, 6.60956721e-05, 6.74434932e-06, 2.75783004e-05,
        5.51655139e-05, 7.21009274e-04, 3.17111611e-03, 2.54080282e-04,
        1.06306898e-03, 6.39173668e-04, 5.52938785e-04, 1.80774362e-06,
        6.96824202e-07, 1.05288409e-01, 8.86774913e-04, 4.66823607e-04,
        8.68424322e-05, 1.99664268e-04, 1.40172197e-02, 5.135015

In [34]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


(1, 283)

In [35]:
import numpy as np
np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


np.int64(112)

In [36]:
pos = np.argmax(model.predict(padded_token_text))

for word, index in tokenizer.word_index.items():
    if index == pos:
        print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
absolutely


In [37]:
text = "mail"

for i in range(5):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
mail absolutely
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
mail absolutely you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
mail absolutely you will
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
mail absolutely you will be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
mail absolutely you will be able


In [38]:
import time
text = "mail"

for i in range(5):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
mail absolutely
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
mail absolutely you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
mail absolutely you will
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
mail absolutely you will be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
mail absolutely you will be able


In [39]:
import time
text = "nlp and deep learning"

for i in range(5):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nlp and deep learning and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nlp and deep learning and nlp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be a part


In [40]:
import time
text = "nlp and deep learning"

for i in range(10):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
nlp and deep learning and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
nlp and deep learning and nlp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
nlp and deep learning and nlp be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nlp and deep learning and nlp be a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be a part
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be a part of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
nlp and deep learning and nlp be a part of this
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
nlp and deep learning and nlp be a part of this program
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nlp and deep learning and nlp be a part of this program what
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nlp and deep learning and nlp be a part of this program what comes


In [41]:
import time
text = "total duration of the course"

for i in range(10):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
total duration of the course fee
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
total duration of the course fee for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
total duration of the course fee for data
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
total duration of the course fee for data science
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
total duration of the course fee for data science mentorship
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
total duration of the course fee for data science mentorship program
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
total duration of the course fee for data science mentorship program dsmp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
total duration of the course fee for data science mentorship program dsmp 2023
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
total duration of the course fee for data science mentorship program dsmp 2023 2023
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
total duration of the course fee for data science mentorship program dsmp 2023 2023 2023


In [42]:
import time
text = "what is the fee"

for i in range(10):

    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = 56, padding = 'pre')
    #predict
    pos = np.argmax(model.predict(padded_token_text))
    
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
what is the fee of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
what is the fee of the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
what is the fee of the mentorship
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
what is the fee of the mentorship program
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
what is the fee of the mentorship program dsmp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
what is the fee of the mentorship program dsmp 2023
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
what is the fee of the mentorship program dsmp 2023 so
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
what is the fee of the mentorship program dsmp 2023 so the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
what is the fee of the mentorship program dsmp 2023 so the total
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
what is the fee of the mentorship program dsmp 2023 so the total course


In [43]:
# More Tasks

# 1. Calculate Validation Accuracy
# 2. Improve Performance
# 2.1 More Data
# 2.2 Hyperparameter Tuning
# 2.3 Advanced Architecture
# 2.3.1 Stacked LSTM
# 2.3.2 Bidirectional LSTM
# 2.3.3 Transformers (GPT||BERT)